---
title: "[COVID-19 Situation Report](https://unlikelyvolcano.com/covid-report.html)"
author:  "[UnlikelyVolcano (David Azizi)](https://unlikelyvolcano.com)"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, out.width = "100%")
confirmed <-
  read.csv(
    "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
  )
deaths <-
  read.csv(
    "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"
  )
recovered <-
  read.csv(
    "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"
  )
```

This report was last updated on `r Sys.Date()`. Data courtesy of [JHU CSSE](https://systems.jhu.edu/research/public-health/ncov/).

[Worldwide report here.](https://unlikelyvolcano.com/covid-world.html)

## United States {.tabset}

```{r us}
us_confirmed <-
  data.frame(
    date = as.Date(names(confirmed), format = "X%m.%e.%y")[-(1:4)],
    cases = colSums(confirmed[confirmed$Country.Region == "US" , -(1:4)], na.rm = T)
  )

new_cases <-
  us_confirmed$cases[-1] - us_confirmed$cases[-nrow(us_confirmed)]
by_day <-
  us_confirmed$cases[-1] / us_confirmed$cases[-nrow(us_confirmed)]
growth_rate <- new_cases[-1] / new_cases[-length(new_cases)]
growth_data <- data.frame(
  date = us_confirmed$date[-(1:2)],
  cases = us_confirmed$cases[-(1:2)],
  change_cases = by_day[-1],
  new_cases = new_cases[-1],
  change_new = growth_rate
)
```

### Cumulative Cases

```{r us:logged}
plot(
  us_confirmed$date,
  log(us_confirmed$cases),
  main = "Cumulative Cases of COVID-19 in the US, Logged",
  pch = 20,
  xlab = "Date",
  ylab = "log(Cases)"
)
lm1 <- lm(log(cases) ~ date, data = us_confirmed)
abline(lm1$coefficients[1], lm1$coefficients[2])
sm1 <- summary(lm1)
text(
  x = us_confirmed$date[us_confirmed$date == "2020-03-18"],
  y = 2,
  labels = paste0("All time: R^2 = ", round(sm1$r.squared, 3)),
  pos = 2
)
lm2 <-
  lm(log(cases) ~ date,
     data = us_confirmed,
     subset = us_confirmed$date > "2020-02-29")
abline(lm2$coefficients[1], lm2$coefficients[2], col = "red")
sm2 <- summary(lm2)
text(
  x = us_confirmed$date[us_confirmed$date == "2020-03-18"],
  y = 1,
  labels = paste0("Since March: R^2 = ", round(sm2$r.squared, 3)),
  col = "red",
  pos = 2
)
```

```{r us:total}
plot(
  us_confirmed,
  main = "Cumulative Cases of COVID-19 in the US",
  pch = 20,
  xlab = "Date",
  ylab = "Cases"
)
```

### Growth Rate

```{r us:growth}
plot(
  growth_data$date,
  growth_data$new_cases,
  main = "New Cases by Day in the US",
  xlab = "Date",
  ylab = "New Cases",
  pch = 20,
  type = "o"
)
```

### Table

```{r us:table}
out <- growth_data[(us_confirmed$date > "2020-02-29")[-(1:2)],]
kable(
  out,
  col.names = c("Date", "Cases", "∂ Cases", "New Cases", "∂ New Cases"),
  row.names = F,
  digits = 3
)
```

