---
title: "COVID-19 Report"
author: "UnlikelyVolcano"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, out.width = "100%")
dta <-
  read.csv(
    "~/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
  )
```

# United States {.tabset}

```{r us}
usa <- data.frame(date = as.Date(names(dta), format = "X%m.%e.%y")[-(1:4)],
                  cases = colSums(dta[dta$Country.Region == "US" , -(1:4)], na.rm = T))

```

## Total Cases in the United States

```{r us:total}
plot(usa, main = "Cases of SARS-CoV-2 in the United States", pch = 20)
```

## Exponential Fit of Cases in the United States

```{r us:logged}
plot(
  usa$date,
  log(usa$cases),
  main = "Logged Cases of SARS-CoV-2 in the United States",
  pch = 20,
  xlab = "Date",
  ylab = "log(Cases)"
)
lm1 <- lm(log(cases) ~ date, data = usa)
abline(lm1$coefficients[1], lm1$coefficients[2])
sm1 <- summary(lm1)
text(
  x = usa$date[nrow(usa) - 5],
  y = 2,
  labels = paste0("R^2 = ", round(sm1$r.squared, 3))
)
lm2 <- lm(log(cases) ~ date, data = usa, subset = usa$date > "2020-02-29")
abline(lm2$coefficients[1], lm2$coefficients[2], col = "red")
sm2 <- summary(lm2)
text(
  x = usa$date[nrow(usa) - 5],
  y = 1,
  labels = paste0("R^2 = ", round(sm2$r.squared, 3)),
  col = "red"
)
```

## Growth Rate in the United States

```{r us:growth}
new_cases <- (usa$cases[-1] - usa$cases[-nrow(usa)])
by_day <- usa$cases[-1] / usa$cases[-nrow(usa)]
growth_rate <- new_cases[-1] / new_cases[-length(new_cases)]
out <- cbind(Date = paste(usa$date[usa$date > "2020-02-29"]),
             Cases = usa$cases[usa$date > "2020-02-29"],
             `∂ Cases` = by_day[(usa$date > "2020-02-29")[-1]],
             `New Cases` = new_cases[(usa$date > "2020-02-29")[-1]],
             `∂ New Cases` = growth_rate[(usa$date > "2020-02-29")[-(1:2)]])
kable(out)
```